### PR TITLE
 Add support for alternative OSs

### PR DESCRIPTION
**Pull request by jackbentley**
Split package and repo tasks into separate task files

Configures role for:
 - Ubuntu
 - Debian
 - CentOS
 - RedHat
 - Fedora

### CODE REVIEW

**Comment by schlueter** [comment]
We don't use rhel distros in house, so you'll have to support them @jackbentley, but I don't see a problem with merging this.

**Comment by schlueter** [comment]
I added Vagrant targets for centos and fedora with https://github.com/refinery29/ansible-openresty-role/pull/9, so if you fix the conflicts and `vagrant up` works, I'll merge this.

**Comment by schlueter** [comment]
@jackbentley thanks for the contrib:)

**Comment by jackbentley** [comment]
Looks good! :D sorry, didn't have time to fix the build. Ping me if you have any issues with rhel - we use it in house for most servers. 

I basically converted all the instructions from https://openresty.org/en/linux-packages.html into Ansible :)

**Pull request merged**
